Account/urls.py
from django.urls import path
from . import views

app_name='Account'
urlpatterns = [
    path('', views.userRole, name='roll'),
    path('candidatepage', views.candidate, name='candidate'),
    path('authoritypage', views.authority, name='authority'),
]

Authority/urls.py
from django.urls import path

from Authority.views import sorted_list_3, home, sorted_list_1, sorted_list_2, sendEmail3, sendEmail2, sendEmail1, authLogin, authRegistration, authLogout

app_name='Authority'
urlpatterns = [

    path('sorted_list_1/', sorted_list_1, name='sorted_list_1'),
    path('sorted_list_2/', sorted_list_2, name='sorted_list_2'),
    path('sorted_list_3/', sorted_list_3, name='sorted_list_3'),
    path('', home, name='sorted_list'),
    path('send_email_3/', sendEmail3, name='send_email_3'),
    path('send_email_2/', sendEmail2, name='send_email_2'),
    path('send_email_1/', sendEmail1, name='send_email_1'),
    path('login', authLogin, name='auth_login'),
    path('registration', authRegistration, name='auth_registration'),
    path('logout', authLogout, name='auth_logout'),
]

CV_Sorting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Account.urls')),
    path('candidate/', include('Candidate.urls')),
    path('authority/', include('Authority.urls')),

]

Authority/models.py
from datetime import datetime
from django.contrib.auth.hashers import make_password
from django.db import models


class Skill(models.Model):
    skill_name = models.CharField(max_length=50)
    score = models.FloatField(default=0)


class TopCandidates(models.Model):
    number_of_selection = models.IntegerField()
    date = models.DateTimeField(default=datetime.now, blank=True)


class Authority(models.Model):

    name = models.CharField(max_length=20)
    username = models.CharField(max_length=8)
    password = models.CharField(max_length=10)


class authority_account(models.Model):
    auth_userid = models.CharField(max_length=100, primary_key=True)
    auth_fullname = models.CharField(max_length=100, blank=False, null=False)
    auth_email = models.CharField(max_length=100, blank=False, null=False)
    auth_pass = models.CharField(max_length=10000, blank=False, null=False)
    auth_phone = models.CharField(max_length=11, blank=False, null=False)

    def save(self, *args, **kwargs):
        self.man_pass = make_password(self.auth_pass)
        super(authority_account, self).save(*args, **kwargs)

    def __str__(self):
        return 'id: {}'.format(self.auth_userid)

Authority/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from . models import authority_account


class authority_account_form(forms.ModelForm):
    auth_email = forms.CharField(widget=forms.EmailInput())
    auth_pass = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = authority_account
        fields = [
            'auth_userid',
            'auth_fullname',
            'auth_email',
            'auth_phone',
            'auth_pass'
        ]


class authority_login_raw_form(forms.Form):
    auth_userid = forms.CharField()
    auth_pass = forms.CharField(widget=forms.PasswordInput())

Authority/views.py
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import authority_account_form, authority_login_raw_form
from Authority.models import TopCandidates
from Candidate.models import Candidate, Resume
from .models import authority_account
from django.contrib.auth.hashers import check_password
from django.urls import reverse


def authLogin(request):
    if request.method == "POST":
        user_id = request.POST['signin-user']
        user_password = request.POST['signin-password']
        print(f"{user_id} and {user_password}")
        login_id = authority_account.objects.filter(auth_userid=user_id)
        print((login_id))
        if login_id:
            is_login_id = authority_account.objects.filter(auth_userid=user_id, auth_pass=user_password)
            # login_pass = is_login_id.auth_pass
            # check_hash = check_password(user_password, login_pass)
            if is_login_id:
                request.session['auth_userid'] = user_id
                print('login successful')
                ses = request.session['auth_userid']

                # return render(request, 'manager/manager_dashboard.html', context)
                return HttpResponseRedirect(reverse('Authority:sorted_list'))
            else:
                print('login failed')
                context = {
                    'msg': 'failed and try again'
                }
                return render(request, 'Authority/login.html', context)
    elif request.session.has_key('auth_userid'):
        print('already has a keyy')
        return render(request, 'Authority/sorted_list.html')
    else:
        context = {
            'msg': 'failed and try again'
        }
        return render(request, 'Authority/login.html', context)


def authRegistration(request):
    form = authority_account_form()
    context = {
        'regForm': form,
        'msgtype': 'failed',
        'message': ''
    }
    if request.method == 'POST':
        form = authority_account_form(request.POST, request.FILES)
        if form.is_valid():
            # user = form.cleaned_data.get('man_userid')
            password1 = form.data['auth_pass']
            password2 = request.POST['man_pass2']
            print(f"{password1} and {password2}")
            if password1 == password2:
                form.save()
                form = authority_account_form()
                context.update({
                    'message': 'Registration is successful',
                    'msgtype': 'successful'
                })
            else:
                form = authority_account_form()
                context.update({
                    'message': ',Password Must be same',
                    'msgtype': 'failed'
                })
            # formuser = form.data['auth_userid']
            # print(formuser)
            # print(user)

        else:
            context.update({
                'message': 'Try Again',
                'msgtype': 'failed'
            })

    return render(request, 'Authority/registration.html', context)


def authLogout(request):
    if request.session.has_key('auth_userid'):
        print('key is deleted')
        del request.session['auth_userid']

    return HttpResponseRedirect(reverse('Authority:auth_login'))


def sorted_list_3(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        candidates = Candidate.objects.all()
        candidates = list(candidates)
        candidates.sort(key=lambda c: c.experiences_skills_combined_score, reverse=True)
        return render(request, "Authority/sorted_list.html", {'candidates': candidates})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))


def sorted_list_2(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        candidates = Candidate.objects.all()
        candidates = list(candidates)
        candidates.sort(key=lambda c: c.skills_score, reverse=True)

        return render(request, "Authority/sorted_list.html", {'candidates': candidates})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))


def sorted_list_1(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        candidates = Candidate.objects.all()
        candidates = list(candidates)
        candidates.sort(key=lambda c: c.total_experiences, reverse=True)

        return render(request, "Authority/sorted_list.html", {'candidates': candidates})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))



def home(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        return render(request, "Authority/sorted_list.html", {})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))



def sendEmail1(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        top_candidates = TopCandidates.objects.all()
        candidates = Candidate.objects.all()
        candidates = list(candidates)
        candidates.sort(key=lambda c: c.total_experiences, reverse=True)
        mailPart(top_candidates, candidates)
        return render(request, "Authority/sorted_list.html", {'candidates': candidates})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))



def sendEmail2(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        top_candidates = TopCandidates.objects.all()
        candidates = Candidate.objects.all()
        candidates = list(candidates)
        candidates.sort(key=lambda c: c.skills_score, reverse=True)
        mailPart(top_candidates, candidates)
        return render(request, "Authority/sorted_list.html", {'candidates': candidates})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))



def sendEmail3(request):
    ses = request.session.has_key('auth_userid')
    if ses:
        top_candidates = TopCandidates.objects.all()
        candidates = Candidate.objects.all()
        candidates = list(candidates)
        candidates.sort(key=lambda c: c.experiences_skills_combined_score, reverse=True)
        mailPart(top_candidates, candidates)
        return render(request, "Authority/sorted_list.html", {'candidates': candidates})
    else:
        return HttpResponseRedirect(reverse('Authority:auth_login'))



def mailPart(top_candidates, candidates):
    count = 1
    for max_can in top_candidates:
        max_candidates = max_can.number_of_selection
        date = max_can.date
        print(max_candidates)
    for can in candidates:
        if count <= max_candidates:
            send_mail(
                'Django Developer Interview',
                'You submitted your CV to Antor Productions. You are cordially invited for the interview. Your score: ' +
                str(can.experiences_skills_combined_score) + '. Position: ' + str(count) + '. Interview Date: ' + str(
                    date) + '.',
                settings.EMAIL_HOST_USER,
                [can.email],
                fail_silently=False,
            )
            count = count + 1

Authority/templates/Authority/authentication_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CV SORTING</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="favicon.ico">

    <!-- FontAwesome JS-->
    <script defer src="{% static 'manager/plugins/fontawesome/js/all.min.js' %}"></script>

    <!-- App CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'manager/css/portal.css' %}">

</head>

<body class="app app-login p-0">
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">
				    <div class="app-auth-branding mb-4"></div>
					<h2 class="auth-heading text-center mb-5">{{usr}} {{login_var}}  Portal</h2>
			        <div class="auth-form-container text-start">
						{% block content %} {% endblock %}
						<div>
							<p>
								{{msg}}
							</p>
						</div>
					</div><!--//auth-form-container-->

			    </div><!--//auth-body-->

			    <!--//app-auth-footer-->
		    </div><!--//flex-column-->
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">

		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->

    </div><!--//row-->


</body>
</html>

Authority/templates/Authority/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>

    <body>

                  <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/authority/home/">Home</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sort By
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/authority/sorted_list_1/">Experiences</a>
                      <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/authority/sorted_list_2/">Skills</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/authority/sorted_list_3/">Both Combination</a>
                  </div>
                </li>


                  <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Send Email
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/authority/send_email_1/">Top scorer (Experiences)</a>
                      <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/authority/send_email_2/">Top scorer (Skills)</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/authority/send_email_3/">Top scorer (Both Exp & Skills)</a>
                  </div>
                </li>

              </ul>
                <ul style="list-style: none">
                    <li>
                        <a href="{% url 'Authority:auth_logout' %}" style="background-color: #6c757d">
                            <button>Log Out</button>
                        </a>
                    </li>
                </ul>

            </div>
          </nav>
        {% block content %}{% endblock %}
    </body>
</html>

Authority/templates/Authority/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CV SHORTING</title>

    <!-- Bootstrap CSS -->
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    /> -->

    <!-- bootswatch theme Zephyr -->
    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

Authority/templates/Authority/login.html
{% extends 'Authority/authentication_base.html' %}
{% block content %}
<form class="auth-form login-form" name="manager_login" method="post">
         {% csrf_token %}
        <div class="email mb-3">
            <label class="sr-only" for="signin-email">User ID</label>
            <input id="signin-email" name="signin-user" type="text" class="form-control signin-email" placeholder="User ID" required="required">
        </div><!--//form-group-->
        <div class="password mb-3">
            <label class="sr-only" for="signin-password">Password</label>
            <input id="signin-password" name="signin-password" type="password" class="form-control signin-password" placeholder="Password" required="required">
            <div class="extra mt-3 row justify-content-between">

            </div><!--//extra-->
        </div><!--//form-group-->
        <div class="text-center">
            <button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
        </div>
</form>

{% endblock %}

Authority/templates/Authority/registration.html
{% extends 'Authority/index.html' %}
{% load crispy_forms_tags %}
{% block content %}

<html>
<head>
    <style>
        .usersignupform{
            margin: auto;
            width: 50%;
            border: 3px solid green;
            padding: 10px;


        }
    </style>
</head>
<body>
    <div class="container mt-3">
    <div class="usersignupform p-3" id="design">
        <h4 class="d-inline-block">Authority Registration</h4>
        <div class="bg-info mb-3" style="padding: 0.5px;"></div>
        <div id="">
            <form action="{% url 'Authority:auth_registration' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ regForm | crispy }}
                <div id="div_id_man_pass" class="form-group">
	                <label for="id_man_pass" class=" requiredField">
                     auth pass 2<span class="asteriskField">*</span>
                    </label>
                    <div class="">
                    <input type="password" name="man_pass2" class="textinput textInput form-control" required="" id="id_man_pass">
                     </div>
                </div>
                <input type="submit" class="btn btn-outline-success btn-sm float-right" value="Register">
            </form>
            <span><a href="login" class="text-secondary" style="font-size:13px">Back to login</a></span>
            <div class="mt-3">
                {% if message %}
                {% if msgtype == "successful" %}
                <p class="alert alert-warning" id="alert-style">{{ message }}</p>
                {% else %}
                <p class="alert alert-danger" id="alert-style">Try Again{{ message }}</p>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

{% endblock %}

Authority/templates/Authority/sorted_list.html
{% extends "Authority/base.html" %}
{% block content %}
<style>
    #customers {
      font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    #customers td, #customers th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #customers tr:nth-child(even){background-color: #f2f2f2;}
    
    #customers tr:hover {background-color: #ddd;}
    
    #customers th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #4CAF50;
      color: white;
    }
    </style>


<table id="customers">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Experiences (Year)</th>
        <th>Number</th>
        <th>Total Skills</th>
        <th>Skills Score</th>
        <th>Skills & Exp Score</th>

    </tr>

    {% for candidate in candidates %}

    <tr>
      <td>{{candidate.name}}</td>
      <td>{{candidate.email}}</td>
      <td>{{candidate.total_experiences}}</td>
      <td>{{candidate.phone}}</td>
      <td>{{candidate.total_skills}}</td>
      <td>{{candidate.skills_score}}</td>
      <td>{{candidate.experiences_skills_combined_score}}</td>
    </tr>

    {% endfor %}

  </table>


{% endblock content %}