Account/urls.py
from django.urls import path
from . import views

app_name='Account'
urlpatterns = [
    path('', views.userRole, name='roll'),
    path('candidatepage', views.candidate, name='candidate'),
    path('authoritypage', views.authority, name='authority'),
]

CV_Sorting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Account.urls')),
    path('candidate/', include('Candidate.urls')),
    path('authority/', include('Authority.urls')),

]

Candidate/urls.py
from django.urls import path

from Candidate import views
from Candidate.views import handleResume, personal, contact, con, canRegistration, CanLogin, CanLogout
from django.conf.urls.static import static

app_name='Candidate'
urlpatterns = [
    path('login', CanLogin, name='login'),
    path('registration', canRegistration, name='registration'),
    path('logout', CanLogout, name='logout'),
    path('', handleResume, name='submitCV'),
    path('personal/', personal, name='personal'),

    path('con/', con, name='con'),
    path('con/contact/', contact, name='contact'),
]

Candidate/models.py
from datetime import datetime
from django.db import models


class Resume(models.Model):
    resumeId = models.AutoField(primary_key=True)
    resume = models.FileField(upload_to='resumes/', blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True)


class Candidate(models.Model):
    candidateId = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20)
    total_experiences = models.FloatField()
    total_skills = models.IntegerField()
    designation = models.CharField(max_length=50)
    company = models.CharField(max_length=100)
    skills_score = models.FloatField()
    experiences_skills_combined_score = models.FloatField()


class Personal(models.Model):

    email = models.EmailField(max_length=100)
    score = models.IntegerField()

    def __str__(self):
        return self.email

Candidate/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "phone_number", "first_name", "last_name", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.phone_number = self.cleaned_data["phone_number"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

Candidate/views.py
import os
from django.shortcuts import render, redirect
from pyresparser import ResumeParser
from Authority.models import Skill
from Candidate.models import Resume, Candidate
from . forms import NewUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

def canRegistration(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        context = {
            'signform': form,
            'message': '',
            'msgtype': 'failed'

        }
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('Candidate:login')
    else:
        form = NewUserForm()
    return render(request, 'Candidate/registration.html',
                  {'signform': form, 'usr': 'Candidate', 'login_var': 'Registration'})


def CanLogin(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('Candidate:submitCV')
    else:
        form = AuthenticationForm()
    return render(request, 'Candidate/login.html', {'form': form, 'usr': 'Candidate', 'login_var': 'Login'})


def CanLogout(request):
    logout(request)
    return redirect('Account:roll')

def personal(request):

    return render(request, 'Candidate/index.html', {})


def con(request):
    return render(request, 'Candidate/contactbase.html', {})


def contact(request):
    return render(request, 'Candidate/contact.html', {})


@login_required(login_url='Candidate:login')
def handleResume(request):

    if request.method == 'POST':
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        print('post')
        resume = request.FILES.get('resume', None)
        print(resume)
        if resume:
            saving = Resume(resume=resume)
            saving.save()
            media_path = os.path.join(base_dir, 'Resumes')
            l_part = str(saving.resume).split('/')
            full_path = os.path.join(media_path, l_part[1])
            data = ResumeParser(str(full_path)).get_extracted_data()
            print(data.get('total_experience'))
            print(data.get('skills'))
            skills = data.get('skills')
            predefined_skill = Skill.objects.all()
            skills_score = 0
            for skill in skills:
                skill = skill.casefold()
                for pre_skill in predefined_skill:
                    if pre_skill.skill_name.casefold() == skill:
                        skills_score = skills_score + pre_skill.score

            print(skills_score)
            experiences_skills_combined_score = float(data.get('total_experience')) + skills_score
            print(experiences_skills_combined_score)
            candidate = Candidate(name=data.get('name'), email=data.get('email'),
                                  phone=data.get('mobile_number'),
                                  total_experiences=float(data.get('total_experience')),
                                  total_skills=len(data.get('skills')),
                                  designation="N/A" if data.get('designation') is None else data.get('designation'),
                                  company="N/A" if data.get('company_names') is None else data.get('company_names'),
                                  skills_score=skills_score,
                                  experiences_skills_combined_score=experiences_skills_combined_score)

            candidate.save()

            return render(request, "Authority/sorted_list.html", {})

    return render(request, "Candidate/cv_form.html", {})

Candidate/templates/Candidate/authentication_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>CV SORTING</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="favicon.ico">

    <!-- FontAwesome JS-->
    <script defer src="{% static 'manager/plugins/fontawesome/js/all.min.js' %}"></script>

    <!-- App CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'manager/css/portal.css' %}">

</head>

<body class="app app-login p-0">
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">
				    <div class="app-auth-branding mb-4"></div>
					<h2 class="auth-heading text-center mb-5">{{usr}} {{login_var}}  Portal</h2>
			        <div class="auth-form-container text-start">
						{% block content %} {% endblock %}
						<div>
							<p>
								{{msg}}
							</p>
						</div>
					</div><!--//auth-form-container-->

			    </div><!--//auth-body-->

			    <!--//app-auth-footer-->
		    </div><!--//flex-column-->
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">

		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->

    </div><!--//row-->


</body>
</html>

Candidate/templates/Candidate/base.html
<!DOCTYPE html>
<html>
    <head>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
          {% load static %}
        <link rel="stylesheet" href="{%static 'css/candidate.css'%}">

    </head>

    <body>
    {% block content %}


    {% endblock %}
    </body>
</html>

Candidate/templates/Candidate/contact.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="viewport" content="width=device-width, initial-scale=1">
	<title>MyProtfolio</title>

   <!-- Custom Bootstrap file -->



	<!--- Custom css file -->
	 {% load static %}
	<link rel="stylesheet" href="{%static 'authority/css/style.css'%}">
</head>
<body>
    {% block content %}

<!-- =============Strat header==---->
<header>
	<nav class="stretchy-nav">
		<a href="#0" class="nav-trigger">
			<span></span>
		</a>
		<ul class="links">
			<li><a class="active" href="#home"><span class=" fa fa-home"></span>Home</a></li>
			<li><a href="#about"><span class="fa fa-user"></span>About</a></li>
			<li><a href="#protfolio"><span class="fa fa-briefcase"></span>Protfolio</a></li>
			<li><a href="#contact"><span class="fa fa-comments"></span>Contact</a></li>
			<li><a href="#blog"><span class="fa fa-envelope-open"></span>Blog</a></li>
		</ul>
		<span class="stretchy-nav-bg"></span>
	</nav>


</header>

<!-- =============Strat header===---->

<!-- =============Strat home========---->
<section class="home">
	<div class="overlay">

	</div>
		<div class="container">
			<div class="row">
				<div class="home-content">
					<div class="pic-box">
						<div class="pic">


						</div>
					</div>
					<div class="text">
						<h3 class="title-text">Hi there!</h3>
						<h1 class="title-text text-uppercase">I am <span>Sonahur Rahman</span> </h1>
						<h4 class="title-text text-uppercase">Junior <span>web Developer</span></h4>
						<p class="">Compared with commercial websites, web developers’ personal websites need to pay more attention to personality and independent thinking. Below, you will find 24 of the best web developer portfolios from both individual designers and creative studios worldwide. Scroll down and get inspired.</p>
						<div class="home-button">
							<a href="#" class="btn-bg"><span class="fa fa-user"></span>More about me</a>
							<a href="#" class="btn-link"><span class="fa fa-briefcase"></span>Protfolio</a>
						</div>

					</div>


				</div>

			</div>
		</div>
	</section>


	<!-- =============end home========---->

	<!-- =============start about========---->
	<section class="about ">
		<div class="conatiner">
			<div class="row">
				<div class="page-title">
					<h1 class="heading">About <span>me</span></h1>
					<p class="sub-heading">I design and code Beautiful things, and i love what i do </p>
				</div>

			</div>
			<!---personal info-->
			<div class="row">
				<div class="personal-info">
					<div class="img-box">
						<img src="{%static 'authority/images/sohnaur1.jpg'%}" alt="sohnaur1">
					</div>
					<div class="info">
						<div class="row">
						 <div class="col-6">
							<ul>
								<li><span>First Name</span> Sohanur</li>
								<li><span>Last Name</span> Rahman</li>
								<li><span>Birth Day</span> 1 jan 1996</li>
								<li><span>Nationality</span> Bangladeshi</li>
								<li><span>Experience</span> 2 years</li>
								<li><span>Address</span> Bogura, Bangladesh</li>


							</ul>
						 </div>
						<div class="col-6">
							<ul>
								<li><span>Freelance</span> Available</li>
								<li><span>Language</span>English</li>
								<li><span>phone</span>01571-784792</li>
								<li class="email"><span>Email</span> sohanurswe@gmail.com</li>
								<li><span>skype</span>sohanur.rahman</li>



							</ul>

						</div>
					  </div>
					  <div class="row">
					  	<div class="cv-btn">
					  		<a href="" class="btn-bg">Download My CV</a>
					  	</div>

					  </div>

					</div>
				</div>

			</div>
			<!-- separator-->
			<div class="row">
				<div class="separator">
					<div class="line">

					</div>
				</div>
			</div>
			<div class="row">
				<div class="resume">
					<div class="row">
						<div class="experience">
							<div class="row">
								<div class="section-title">
									<h3>Experience </h3>
								</div>
							</div>
							<div class="row">
								<div class="details">
									<div class="card">
										<div class="circle"></div>
										<h6 class="date"><span class="fa fa-calendar"></span>2017 -2019</h6>
										<h4 class="position">Web Developer<span class="separator"></span>djksdsk</h4>
										<p>Lorem ipsum dolor sit amet, consider adipiscing elit , sed diem normaly nidnn akdjks sdkjcnsdk dimsdn.</p>

									</div>
									<div class="card">
										<div class="circle"></div>
										<h6 class="date"><span class="fa fa-calendar"></span>2017 -2019</h6>
										<h4 class="position">Web Developer<span class="separator"></span>Envator</h4>
										<p>Lorem ipsum dolor sit amet, consider adipiscing elit , sed diem normaly nidnn akdjks sdkjcnsdk dimsdn.</p>

									</div>
									<div class="card">
										<div class="circle"></div>
										<h6 class="date"><span class="fa fa-calendar"></span>2016 -2018</h6>
										<h4 class="position">Web proggraming <span class="separator"></span><span class="bold"></span>Envator</h4>
										<p>Lorem ipsum dolor sit amet, consider adipiscing elit , sed diem normaly nidnn akdjks sdkjcnsdk dimsdn.</p>

									</div>
								</div>

							</div>
						</div>
						<div class="education">
							<div class="row">
								<div class="section-title">
									<h3>Education </h3>
								</div>
							</div>
							<div class="row">
								<div class="details">
									<div class="card">
										<div class="circle"></div>
										<h6 class="date"><span class="fa fa-calendar"></span> 2017 -2019</h6>
										<h4 class="degree">Bachelor Degree<span class="separator"></span><span class="bold">Daffodil International University</span></h4>
										<p>Lorem ipsum dolor sit amet, consider adipiscing elit , sed diem normaly nidnn akdjks sdkjcnsdk dimsdn.</p>

									</div>
									<div class="card">
										<div class="circle"></div>
										<h6 class="date"><span class="fa fa-calendar"></span> 2017 -2019</h6>
										<h4 class="degree">HSC<span class="separator"></span><span class="bold">Govt Shasultan Collage</span></h4>
										<p>Lorem ipsum dolor sit amet, consider adipiscing elit , sed diem normaly nidnn akdjks sdkjcnsdk dimsdn.</p>

									</div>
									<div class="card">
										<div class="circle"></div>
										<h6 class="date"><span class="fa fa-calendar"></span> 2017 -2019</h6>
										<h4 class="degree">SSC<span class="separator"></span><span class="bold">Bogura Coronation Institution School </span></h4>
										<p>Lorem ipsum dolor sit amet, consider adipiscing elit , sed diem normaly nidnn akdjks sdkjcnsdk dimsdn.</p>

									</div>

								</div>
							</div>
						</div>
					</div>
					<!-- Skills--->

					<div class="row">
						<div class="skills">
							<div class="row">
								<div class="section-title">
									<h3>Skills </h3>
								</div>
							<div class="items">

							    <h4>Html</h4>
								  <div class="skill-bar">
									<div class="skill-bar-in" style="width: 80%">
									  <span>80%</span>
									</div>
								  </div>

							</div>
							<div class="items">

									<h4>Java Script</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 60%">
											<span>60%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>Css</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 70%">
											<span>70%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>jQuery</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 55%">
											<span>55%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>Angular JR</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 50%">
											<span>50%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>Wordpress</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 80%">
											<span>80%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>Illustrator</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 60%">
											<span>60%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>After Effects</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 60%">
											<span>60%</span>
										</div>
									</div>

							</div>
							<div class="items">

									<h4>Photoshop</h4>
									<div class="skill-bar">
										<div class="skill-bar-in" style="width: 80%">
											<span>80%</span>
										</div>
									</div>

							</div>
						 </div>
						</div>
					</div>
					<!--- end skills-->
				</div>
			</div>

		</div>

	</section>


	<!-- =============end about========---->

	<!-- =============start protfolio========---->

    <section class="protfolio">
		<div class="conatiner">
			<div class="row">
				<div class="page-title">
					<h1 class="heading">my <span>Protfolio</span> </h1>
					<p class="sub-heading">A few Recent Design and Coding project.Want see more? Email me </p>
				</div>

			</div>
			<div class="protfolio-items">
                <!--item -->
				<div class="item" data-format="image-format">
					<div class="box">
						<div class="img">
							<img src="{%static 'authority/images/protfolio/pro1.jpg'%}" alt="project">
							<div class="item-ovarly">
							
							</div>
						</div>
						<div class="project-info">
							<span class="project">Website</span>
							<span class="client">Sohanur</span>
							<span class="duration">3 Month</span>
							<span class="technologies">Html, Javascript</span>
							<span class="budget">45000 tk </span>
						</div>
					</div>
				</div>
				<!--item end-->
				 <!--item -->
				<div class="item" data-format="image-format">
					<div class="box">
						<div class="img">
							<img src="{%static 'authority/images/protfolio/pro1.jpg'%}" alt="project">
							<div class="item-ovarly">

							</div>
						</div>
						<div class="project-info">
							<span class="project">Website</span>
							<span class="client">Sohanur</span>
							<span class="duration">3 Month</span>
							<span class="technologies">Html, Javascript</span>
							<span class="budget">45000 tk </span>
						</div>
					</div>
				</div>
				<!--item end-->
				 <!--item -->
				<div class="item" data-format="image-format">
					<div class="box">
						<div class="img">
							<img src="{%static 'authority/images/protfolio/pro1.jpg'%}" alt="project">
							<div class="item-ovarly">

							</div>
						</div>
						<div class="project-info">
							<span class="project">Website</span>
							<span class="client">Sohanur</span>
							<span class="duration">3 Month</span>
							<span class="technologies">Html, Javascript</span>
							<span class="budget">45000 tk </span>
						</div>
					</div>
				</div>
				<!--item end-->

			</div>
		</div>
	</section>



	<!-- =============end protfolio========---->


<script src="{%static 'authority/js/script.js'%}"></script>

 {% endblock %}

</body>
</html>

Candidate/templates/Candidate/contactbase.html
<!DOCTYPE html>
<html>
<head>
<title>contact page</title>
     {% load static %}
        <link rel="stylesheet" href="{%static 'css/contactbase.css'%}">
</head>
<body>
  {% block content %}
<h1>CONTACT US</h1>
<div class="name">
    <span  class="pappu" style="text-decoration: none;"> <a href="contact"> Sohanur </a></span>
     <span class="antor" style="text-decoration: none;"> <a href="#">Mazarul</a></span>
     <span class="minhaz" style="text-decoration: none;"> <a href="#">Minhaz</a></span>
</div>
 {% endblock %}
</body>
</html>

Candidate/templates/Candidate/cv_form.html
{% extends 'Candidate/base.html' %}

{% block content %}

    <div style="margin-bottom: 20px">
        <div>
            {% if user.is_authenticated %}
                <a class="nav-link" href="#" style="color:red">hello {{user}}</a>
                <a class="nav-link" href="{% url 'Candidate:logout' %}">
                    <button>Log Out</button>
                </a>

              {% endif %}
        </div>
    </div>

<form action="{% url 'Candidate:submitCV' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

    <div class="form-group">
      <label for="exampleFormControlFile1">Upload your CV/Resume</label>
      <input type="file" name="resume" class="form-control-file" id="exampleFormControlFile1">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="personal" style="font-size:17px; color: red; font-style:italic; font-decoration:none;">Sort Interview</a>
   <a href="con" style="font-size:17px; color: blue; font-style:italic; font-decoration:none;">Contact Us </a>

  </form>

{% endblock content %}

Candidate/templates/Candidate/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>cv sorting</title>
      <link href="https://fonts.googleapis.com/css?family=Teko&display=swap" rel="stylesheet">
      {% load static %}
        <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous" defer></script>
    <script src="{%static 'js/main.js'%}" defer></script>
  </head>
  <body>
    {% block content %}
    <div class="header">

  </div>
  <div class="quizpage">
    <h2>Personal Assesment</h2><br><br>

    <h4>Solve the question:</h4><br><br>
    <div class="question">

      <form id="quiz" name="quiz">
        <p>1. Which of the following is a non functional requirement of a web based application?</p><br>
        <input type="radio"  name="ques1" value="1"> When the user clicks a "read me" link, the color of the link should change from blue to pink <br>
        <input type="radio"  name="ques1" value="2"> When the user clicks a "read me" link, the next page should be opend within 5 seconds <br>
        <input type="radio"  name="ques1" value="3"> When the user clicks a "read me" link, the mouse over should show the target page title in a tool tip <br>
        <input type="radio"  name="ques1" value="4"> When the user clicks a "read me" link, the read me page should load successfully without errors<br><br><br>

        <p>2. A scrum is actually a</p><br>
        <input type="radio"  name="ques2" value="1"> software process model which is agile in nature <br>
        <input type="radio"  name="ques2" value="2"> None of the above <br>
        <input type="radio" name="ques2" value="4"> team pack in rugby where everyone in the pack act together to move the ball down the field <br><br><br>


        <p>3.  ___________ enhances performance and functionality of the software after delivery</p><br>
        <input type="radio"  name="ques3" value="1"> re-design <br>
        <input type="radio"  name="ques3" value="2"> re-engineering <br>
        <input type="radio" name="ques3" value="3"> re-maintenance <br>
        <input type="radio"  name="ques3" value="4"> re-post checking <br><br><br>






        <p>4. Which of the following is not a design tool?</p><br>
        <input type="radio"  name="ques4" value="1"> Simple SUMI<br>
        <input type="radio"  name="ques4" value="2"> Rational Rose <br>
        <input type="radio"  name="ques4" value="3"> Rhapsody <br>
        <input type="radio"  name="ques4" value="4"> Rational Robot <br><br><br>

        <p>5. Backtracking is not possible in the iterative and incremental development approach.</p><br>
        <input type="radio"  name="ques5" value="1"> True<br>
        <input type="radio" name="ques5" value="2"> False <br><br><br>



        <p>6. XP with reference to software development methodology is</p><br>
        <input type="radio"  name="ques6" value="1"> Excellent programming <br>
        <input type="radio"  name="ques6" value="2"> Extreme processing <br>
        <input type="radio"  name="ques6" value="3"> Extreme programming <br>
        <input type="radio"  name="ques6" value="4"> Excellent processing<br><br><br>





        <p>7. CMMi has an iterative lifecycle when compared to CMM.</p><br>
        <input type="radio"  name="ques7" value="1"> True <br>
        <input type="radio"  name="ques7" value="2"> False <br><br><br>

        <p>8. CMM is</p><br>
        <input type="radio"  name="ques8" value="1"> Company maturity model<br>
        <input type="radio"  name="ques8" value="2"> Capability maturity model<br>
        <input type="radio" name="ques8" value="3"> Configuration maturity model<br>
        <input type="radio"  name="ques8" value="4"> Company management model <br><br><br>



        <p>9.  Which of the following is not a graphical modelling language for software design?</p><br>
        <input type="radio"  name="ques9" value="1"> UML <br>
        <input type="radio"  name="ques9" value="2"> DML<br>
        <input type="radio"  name="ques9" value="3"> EEML<br>
        <input type="radio"  name="ques9" value="4"> SysML<br><br><br>

        <p>10. Post implementation review is</p><br>
        <input type="radio"  name="ques10" value="1"> reviewing the risk baseline <br>
        <input type="radio" name="ques10" value="2"> reviewing the traceability matrix<br>
        <input type="radio"  name="ques10" value="3"> reviewing the impact on customers<br>
        <input type="radio"  name="ques10" value="4"> None of the above <br><br>






      </form>
      <button id="button" onclick="">Submit</button>
        <div id="aftarSubmit">
          <p id="message"></p>
          <p id="curretNumber"></p>

        </div>


    </div>

  </div>
 {% endblock %}
  </body>
</html>

Candidate/templates/Candidate/login.html
{% extends 'Candidate/authentication_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-3">
    <div class="userloginform">
        <h4 class="d-inline-block mb-2">Customer Login</h4>
        <div class="bg-info mb-3" style="padding: 0.5px;"></div>
        <div id="">
            <form class="site-form" action="{% url 'Candidate:login' %}" method="post">
                <div class="logging-form">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Login" class="btn" />
                </div>
        </form>

    <div>
        {% for msg in messages %}
        <h3>{{msg}}</h3>
        {% endfor %}
    </div>
            <span style="font-size: 13px;">Not Registered? <a href="{% url 'Candidate:registration' %}">Sign Up</a></span>
       <!--     <div class="mt-3">
                {% if message %}
                <p class="alert alert-danger" id="alert-style">{{ message }}</p>
                {% endif %}
            </div> -->
        </div>
    </div>
</div>
{% endblock %}

Candidate/templates/Candidate/registration.html
{% extends 'Candidate/authentication_base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<html>
<head>

</head>
<body>
    <div class="container mt-3">
    <div class="usersignupform p-3" id="design">

        <div class="bg-info mb-3" style="padding: 0.5px;"></div>
        <div id="">
            <form class="site-form" action="{% url 'Candidate:registration' %}" method="post">
            {% csrf_token %}
            {{ signform|crispy }}
            <input type="submit" value="Signup" class="btn-sm app-btn-secondary">
            </form>
            <span><a href="{% url 'Candidate:login' %}" class="text-secondary" style="font-size:13px">Back to login</a></span>
            <div class="mt-3">
                {% if message %}
                {% if msgtype == "successful" %}
                <p class="alert alert-warning" id="alert-style">{{ message }}</p>
                {% else %}
                <p class="alert alert-danger" id="alert-style">{{ message }} and try again</p>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

{% endblock %}